<a href="https://colab.research.google.com/github/rizkypratamayudha/dataMining/blob/main/ANN_Percobaan_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import library

In [12]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

#load dataset iris
iris = load_iris()
x = iris.data
y = iris.target

#split data untuk training dan testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Standarisasi fitur
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

#Inisialisasi dan pelatihan model MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(2,),max_iter=500, alpha=0.01, solver='adam', random_state=42)
mlp.fit(x_train, y_train)

#Prediksi pada data
y_pred = mlp.predict(x_test)

#Evaluasi Model
accuracy = accuracy_score(y_test,y_pred)
print(f'Akurasi : {accuracy * 100}%')
print (classification_report(y_test, y_pred, target_names=iris.target_names))

#Menampilkan arsitektur neural network
print("\nArsitektur Neural Network: ")
print(f"Input Layer : {x_train.shape[1]} neurons")
for i, size in enumerate(mlp.hidden_layer_sizes):
  print(f"Hidden Layer {i+1}: {size} neurons")
  print(f"Output Layer : {mlp.n_outputs_} neurons")
  print(f"Fungsi Aktivasi : {mlp.activation}")

#jika ingin melihat bobot dan bias hasil pelatihan
print("\nBobot dan bias : ")
print("Bobot antara input dan hidden layer : ")
print(mlp.coefs_[0])
print("Bobot antara hidden dan output layer : ")
print(mlp.coefs_[1])
print("Bias dari hidden layer : ")
print(mlp.intercepts_[0])
print("Bias dari output layer : ")
print(mlp.intercepts_[1])

Akurasi : 50.0%
              precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        10
  versicolor       0.29      0.44      0.35         9
   virginica       0.69      1.00      0.81        11

    accuracy                           0.50        30
   macro avg       0.32      0.48      0.39        30
weighted avg       0.34      0.50      0.40        30


Arsitektur Neural Network: 
Input Layer : 4 neurons
Hidden Layer 1: 2 neurons
Output Layer : 3 neurons
Fungsi Aktivasi : relu

Bobot dan bias : 
Bobot antara input dan hidden layer : 
[[ 0.17464148  1.39583283]
 [ 0.04365591 -0.23615075]
 [-0.2635151  -0.12595657]
 [-0.45936094  1.31232884]]
Bobot antara hidden dan output layer : 
[[-0.70784718  0.69470257  0.36779853]
 [-1.19174309 -0.60616551 -0.24568763]]
Bias dari hidden layer : 
[-0.22562313  1.122528  ]
Bias dari output layer : 
[ 0.06335432 -0.28677109 -0.8247034 ]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and 